// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project
//
// SPDX-License-Identifier: Apache-2.0

#include "include/Verifier.hpp"
#include "include/VerifyAction.hpp"

#include "ClangToolUtils.hpp"
#include "CliArgs.hpp"
#include "DebugLog.hpp"
#include "HarnessHeaderData.hpp"
#include "WorkerPool.hpp"

#include <clang/Frontend/FrontendActions.h>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <llvm/ADT/StringRef.h>
#include <llvm/Support/raw_ostream.h>
#include <memory>
#include <regex>
#include <set>
#include <string>
#include <system_error>
#include <unistd.h>
#include <vector>

// Mirrors Transformer's own fallback default, so a bare Verifier invocation
// lines up with the rest of the "repos" -> "repos-benchmarks" chain.
const std::string defaultTransformDir = "repos-transformed";

const std::string argvCProjectUrl = "https://github.com/unl-pal/argv-c-transformer";

// The two "Generated by..." lines shared by every benchmark .c and .yml header.
static std::string provenanceComment(const std::string &marker) {
  return marker + " Generated by argv-c " ARGV_C_VERSION " (" ARGV_C_COMMIT ")\n" + marker + " " +
         argvCProjectUrl + "\n";
}

Verifier::Verifier(std::string configFile, std::string inputPath) : configuration() {
  config = parsePipelineConfig(configFile);
  configuration.debugLevel = config.fileSettings.at("debugLevel");
  configuration.keepCompilesOnly = config.fileSettings.at("keepCompilesOnly") != 0;
  configuration.fileTimeoutSecs = config.fileSettings.at("fileTimeoutSecs");
  configuration.nproc = config.fileSettings.at("nproc");
  configuration.cleanOutput = config.fileSettings.at("cleanOutput") != 0;
  configuration.transformDir =
      config.transformDir.empty() ? defaultTransformDir : config.transformDir;
  if (!inputPath.empty()) configuration.transformDir = inputPath;
  configuration.benchmarkDir = config.benchmarkDir.empty()
                                   ? inputBaseName(configuration.transformDir) + "-benchmarks"
                                   : config.benchmarkDir;
  globalDebugLevel() = configuration.debugLevel;
}

bool Verifier::verifyFile(std::filesystem::path path) {
  debugLog(1, "[verify] file: " + path.string());
  if (!std::filesystem::exists(path)) {
    debugLog(1, "[verify] path does not exist: " + path.string());
    return false;
  }

  // Shared state the driver reads back after the tool run: fresh counts (for
  // property selection) and the rejected names.
  auto counts = std::make_shared<std::unordered_map<std::string, CountingVisitor::attributes>>();
  auto toRemove = std::make_shared<std::vector<std::string>>();
  HarnessSplit split;

  VerifyActionFactory factory(&config.complexity, &config.features, counts, toRemove, split);
  if (!runToolOnFile(path.string(), factory)) {
    debugLog(1, "[verify] clang tool failed on: " + path.string());
    return false;
  }
  if (split.entries.empty()) {
    debugLog(1, "[verify] discarded (harness empty after re-check): " + path.string());
    return false;
  }

  // Transform output is already flat, so the combined file keeps the filename.
  std::filesystem::path combinedPath =
      std::filesystem::path(configuration.benchmarkDir) / path.filename();
  std::filesystem::create_directories(combinedPath.parent_path());
  std::string header = provenanceComment("//");
  std::string allBlocks;
  for (const HarnessEntry &entry : split.entries)
    allBlocks += entry.block;
  if (!writeText(combinedPath, header + split.head + allBlocks + split.tail)) return false;

  // One check covers every benchmark: each is the combined file minus whole blocks.
  if (!checkCompilable(combinedPath)) {
    if (configuration.keepCompilesOnly) {
      debugLog(1, "[verify] discarded (fails compile check): " + combinedPath.string());
      cleanupPartialOutput(path);
      return false;
    }
    // Kept for inspection, but not a benchmark: no task file, no .i. Left on
    // disk deliberately, so no cleanup here - and none from the pool either,
    // which never touches a child that exited under its own control.
    debugLog(1,
             "[verify] kept but not a benchmark (fails compile check): " + combinedPath.string());
    return false;
  }
  std::error_code ec;
  std::filesystem::remove(combinedPath, ec);

  bool produced = false;
  for (const HarnessEntry &entry : split.entries) {
    std::filesystem::path outPath = splitPath(combinedPath, entry.target);
    if (!writeText(outPath, header + split.head + entry.block + split.tail)) continue;
    writeBenchmarkTask(outPath, targetCounts(*counts, entry.target));
    if (!preprocess(outPath)) {
      debugLog(0, "Preprocessing failed, discarding: " + outPath.string());
      removeBenchmark(outPath);
      continue;
    }
    produced = true;
  }
  return produced;
}

std::filesystem::path Verifier::splitPath(const std::filesystem::path &basePath,
                                          const std::string &target) {
  return basePath.parent_path() /
         (basePath.stem().string() + "__" + target + basePath.extension().string());
}

bool Verifier::writeText(const std::filesystem::path &path, const std::string &text) {
  std::ofstream out(path);
  out << text;
  if (out) return true;
  debugLog(0, "Cannot write output file " + path.string());
  return false;
}

std::unordered_map<std::string, CountingVisitor::attributes>
Verifier::targetCounts(const std::unordered_map<std::string, CountingVisitor::attributes> &counts,
                       const std::string &target) {
  std::unordered_map<std::string, CountingVisitor::attributes> result;
  // reach_error is recorded file-wide, not per function; an assert in an
  // unharnessed sibling only adds unreach-call with a verdict that still holds.
  for (const std::string &name : {target, std::string("reach_error")})
    if (auto it = counts.find(name); it != counts.end()) result.insert(*it);
  return result;
}

void Verifier::removeBenchmark(const std::filesystem::path &cPath) {
  std::error_code ec;
  for (const char *ext : {".c", ".yml", ".i"}) {
    std::filesystem::path p = cPath;
    std::filesystem::remove(p.replace_extension(ext), ec);
  }
}

void Verifier::cleanupPartialOutput(std::filesystem::path path) {
  std::filesystem::path combinedPath =
      std::filesystem::path(configuration.benchmarkDir) / path.filename();
  std::filesystem::path input = std::filesystem::weakly_canonical(path);
  std::string prefix = combinedPath.stem().string() + "__";
  std::error_code ec;
  // transformDir == benchmarkDir makes the combined file the input itself.
  if (std::filesystem::weakly_canonical(combinedPath) != input) removeBenchmark(combinedPath);
  for (const std::filesystem::directory_entry &entry :
       std::filesystem::directory_iterator(combinedPath.parent_path(), ec)) {
    if (ec) break;
    const std::filesystem::path &candidate = entry.path();
    if (candidate.extension() != ".c" || !candidate.stem().string().starts_with(prefix)) continue;
    if (std::filesystem::weakly_canonical(candidate) != input) removeBenchmark(candidate);
  }
}

void Verifier::collectCFiles(std::filesystem::path path,
                             std::vector<std::filesystem::path> &files) {
  if (!std::filesystem::exists(path)) {
    debugLog(1, "[verify] path does not exist: " + path.string());
    return;
  }
  if (std::filesystem::is_directory(path)) {
    for (const std::filesystem::directory_entry &entry :
         std::filesystem::directory_iterator(path)) {
      collectCFiles(entry.path(), files);
    }
    return;
  }
  if (std::filesystem::is_regular_file(path)) {
    if (path.extension() == ".c") {
      files.push_back(path);
    } else {
      debugLog(3, "[verify] skipped (not .c): " + path.filename().string());
    }
    return;
  }
  debugLog(3, "[verify] ignored: " + path.filename().string());
}

WorkerPoolResult Verifier::verifyAll(std::filesystem::path path) {
  std::vector<std::filesystem::path> files;
  collectCFiles(path, files);
  _totalProcessed = static_cast<int>(files.size());

  int workers = resolveWorkerCount(configuration.nproc);
  debugLog(1, "[verify] worker pool size: " + std::to_string(workers));
  std::cout << "[verify] processing " << files.size() << " file(s) with " << workers << " worker(s)"
            << std::endl;

  IsolatedWork work;
  work.child = [this](const std::filesystem::path &p) {
    bool produced = verifyFile(p);
    std::cout.flush();
    std::cerr.flush();
    _exit(produced ? kProducedExit : kDeclinedExit);
  };
  work.runInProcess = [this](const std::filesystem::path &p) { return verifyFile(p); };
  work.cleanupPartial = [this](const std::filesystem::path &p) { cleanupPartialOutput(p); };
  work.debugLog = [](int level, const std::string &msg) { debugLog(level, "[verify] " + msg); };
  work.label = "verify";

  return runWorkerPool(files, workers, configuration.fileTimeoutSecs, work);
}

namespace {

std::string summarizeCompileFailure(const std::string &diagnostics) {
  std::istringstream lines(diagnostics);
  std::string line, firstError;
  int errorCount = 0;
  while (std::getline(lines, line)) {
    if (line.find("error:") == std::string::npos)
      continue;
    ++errorCount;
    if (firstError.empty())
      firstError = line;
  }
  if (firstError.empty())
    return diagnostics.substr(0, 200);
  if (errorCount > 1)
    firstError += " (+" + std::to_string(errorCount - 1) + " more )";
  return firstError;
}

} // namespace

bool Verifier::checkCompilable(std::filesystem::path path) {
  std::unique_ptr<clang::tooling::FrontendActionFactory> factory =
      clang::tooling::newFrontendActionFactory<clang::SyntaxOnlyAction>();
  std::string diagnostics;
  bool ok = runFrontendActionCheckingErrors(path.string(), {}, *factory, &diagnostics);
  if (!ok)
    debugLog(3, "[verify] compile check failed: " + path.string() + ": " +
                    summarizeCompileFailure(diagnostics));
  return ok;
}

std::vector<BenchmarkProperty> Verifier::selectProperties(
    const std::unordered_map<std::string, CountingVisitor::attributes> &counts) {
  std::vector<BenchmarkProperty> properties;
  if (counts.count("reach_error")) properties.push_back({"../properties/unreach-call.prp", true});
  bool loopsPresent = false;
  bool intArithPresent = false;
  bool memsafetyPresent = false;
  for (const auto &[name, attr] : counts) {
    if (!loopsPresent && (attr.Complexity.ForLoops || attr.Complexity.WhileLoops)) {
      loopsPresent = true;
      properties.push_back({"../properties/termination.prp", true});
    }
    if (!intArithPresent && attr.Complexity.Operations) {
      // The operations check is pretty naive as it counts any/all binary and unary operations with
      // side effects
      intArithPresent = true;
      properties.push_back({"../properties/no-overflow.prp", true});
    }
    // valid-memsafety.prp bundles deref/free/memtrack CHECKs in one file
    if (!memsafetyPresent &&
        (attr.Features.PointerDeref || attr.Features.MemAlloc || attr.Features.MemFree)) {
      memsafetyPresent = true;
      properties.push_back({"../properties/valid-memsafety.prp", true});
    }
    if (loopsPresent && intArithPresent && memsafetyPresent) break;
  }
  return properties;
}

void Verifier::writeBenchmarkTask(
    std::filesystem::path cPath,
    const std::unordered_map<std::string, CountingVisitor::attributes> &counts) {
  std::filesystem::path ymlPath = cPath;
  ymlPath.replace_extension(".yml");

  std::string inputFile = cPath.stem().string() + ".i";
  std::vector<BenchmarkProperty> properties = selectProperties(counts);

  std::ofstream out(ymlPath);
  if (!out) {
    debugLog(0, "Failed to write task file: " + ymlPath.string());
    return;
  }

  out << provenanceComment("#")
      << "format_version: '2.0'\n"
      << "\n"
      << "input_files: '" << inputFile << "'\n"
      << "\n";
  if (properties.empty()) {
    out << "properties: []\n";
  } else {
    out << "properties:\n";
    for (const BenchmarkProperty &prop : properties) {
      out << "  - property_file: " << prop.propertyFile << "\n"
          << "    expected_verdict: " << (prop.expectedVerdict ? "true" : "false") << "\n";
    }
  }
  out << "\n"
      << "options:\n"
      << "  language: C\n"
      << "  data_model: LP64\n";
  if (properties.empty()) debugLog(1, "[verify] WARN: no properties found for " + cPath.string());
}

namespace {

// Lines matching one of these are pure header noise. Each entry is a case a specific verifier
// frontend chokes on despite the declaration being semantically inert.
//
// - _Float16/32/64/128(x): glibc's <bits/floatn-common.h> fallback typedefs
//   for the C23 extended float types, pulled in transitively by <stdio.h>
const std::vector<std::regex> &knownNoiseTypedefs() {
  static const std::vector<std::regex> patterns = {
      std::regex(R"(^\s*typedef\s+.+\s_Float\d+x?\s*;\s*$)"),
  };
  return patterns;
}

// Strips knownNoiseTypedefs() lines from an already-preprocessed .i file.
void stripNoiseTypedefs(const std::filesystem::path &iPath) {
  std::ifstream in(iPath);
  if (!in) return;
  std::vector<std::string> kept;
  std::string line;
  bool changed = false;
  while (std::getline(in, line)) {
    bool isNoise = false;
    for (const std::regex &pattern : knownNoiseTypedefs()) {
      if (std::regex_match(line, pattern)) {
        isNoise = true;
        break;
      }
    }
    if (isNoise) {
      changed = true;
      continue;
    }
    kept.push_back(std::move(line));
  }
  in.close();
  if (!changed) return;
  std::ofstream out(iPath, std::ios::trunc);
  for (const std::string &l : kept)
    out << l << "\n";
}

// A typedef may legally repeat verbatim - glibc's own headers commonly reach the
// same typedef (e.g. size_t) through more than one internal path, and C allows
// redeclaring a typedef to the same type any number of times. Some verifier
// frontends (e.g. Ultimate Automizer) reject the redeclaration anyway, even
// though it is valid C
void dedupeExactTypedefLines(const std::filesystem::path &iPath) {
  static const std::regex typedefLine(R"(^\s*typedef\s+.+;\s*$)");
  std::ifstream in(iPath);
  if (!in)
    return;
  std::vector<std::string> kept;
  std::set<std::string> seenTypedefs;
  std::string line;
  bool changed = false;
  while (std::getline(in, line)) {
    if (std::regex_match(line, typedefLine) && !seenTypedefs.insert(line).second) {
      changed = true;
      continue;
    }
    kept.push_back(std::move(line));
  }
  in.close();
  if (!changed)
    return;
  std::ofstream out(iPath, std::ios::trunc);
  for (const std::string &l : kept)
    out << l << "\n";
}

} // namespace

bool Verifier::preprocess(std::filesystem::path cPath) {
  std::filesystem::path iPath = cPath;
  iPath.replace_extension(".i");

  std::unique_ptr<clang::tooling::FrontendActionFactory> factory =
      clang::tooling::newFrontendActionFactory<clang::PrintPreprocessedAction>();
  bool ok = runFrontendActionCheckingErrors(
      cPath.string(), {"-E", "-P", "-std=gnu11", "-o", iPath.string()}, *factory);
  if (!ok) return false;
  stripNoiseTypedefs(iPath);
  dedupeExactTypedefLines(iPath);
  return true;
}

void Verifier::writeHarnessHeader() {
  std::filesystem::create_directories(configuration.benchmarkDir);
  std::ofstream out(std::filesystem::path(configuration.benchmarkDir) / kArgvCHarnessHeaderName);
  out << kArgvCHarnessHeaderContents;
}

int Verifier::run() {
  auto startTime = std::chrono::steady_clock::now();
  std::filesystem::path path(configuration.transformDir);
  if (!std::filesystem::exists(path)) {
    debugLog(0, "Transform directory not found: " + configuration.transformDir);
    return 0;
  }
  checkOrCleanOutputDir(configuration.benchmarkDir, {configuration.transformDir, config.databaseDir},
                        configuration.cleanOutput);
  writeHarnessHeader();
  WorkerPoolResult result = verifyAll(path);
  std::cout << "\n=== Verify summary ===\n"
            << "  Files processed:        " << _totalProcessed << "\n"
            << "  Benchmarks produced:    " << result.produced << "\n"
            << "  Declined (no output):   " << result.declined << "\n"
            << "  Failed:                 " << result.failed << "\n"
            << "  Time elapsed:           "
            << formatElapsed(std::chrono::steady_clock::now() - startTime) << std::endl;
  return result.produced;
}
