/* SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Runtime scaffolding for benchmarks generated by argv-c.
 *
 * This exact file is copied verbatim into every benchmark's output
 * directory (once per directory, since Verifier's output is flat) and
 * #included by each generated .c. The pipeline preprocesses every benchmark
 * to a .i as its final step (see argv-c-transformer's "Preprocessing Late,
 * Not Early" design note), so this header is fully inlined into the
 * artifact a verifier actually consumes - only the .c stays short and
 * readable for a human to audit.
 *
 * __VERIFIER_nondet_* declarations are SV-Comp's contract: a verifier
 * supplies the real definitions at analysis time. The __HAVOC_* macros and
 * helpers below are this project's own scaffolding for synthesizing bounded
 * nondet pointers, strings, and argv/argc - see HavocCallsVisitor and
 * MainGenConsumer in the argv-c-transformer source for what emits calls
 * into this file.
 */

#ifndef ARGV_C_RUNTIME_H
#define ARGV_C_RUNTIME_H

#include <assert.h>
#include <stdlib.h>
#include <stddef.h>

/* SV-Comp nondet primitives. Declaring all of them unconditionally is
 * harmless - an unused extern declaration costs nothing. */
extern _Bool __VERIFIER_nondet_bool(void);
extern char __VERIFIER_nondet_char(void);
extern unsigned char __VERIFIER_nondet_uchar(void);
extern short __VERIFIER_nondet_short(void);
extern unsigned short __VERIFIER_nondet_ushort(void);
extern int __VERIFIER_nondet_int(void);
extern unsigned int __VERIFIER_nondet_uint(void);
extern long __VERIFIER_nondet_long(void);
extern unsigned long __VERIFIER_nondet_ulong(void);
extern long long __VERIFIER_nondet_longlong(void);
extern unsigned long long __VERIFIER_nondet_ulonglong(void);
extern float __VERIFIER_nondet_float(void);
extern double __VERIFIER_nondet_double(void);
extern size_t __VERIFIER_nondet_size_t(void);

/* Fills [mem, mem+size) with nondet bytes. Standard SV-Comp function; a
 * verifier supplies the real definition. mem must be a valid pointer to a
 * block of exactly `size` bytes - never dereference a raw nondet pointer
 * value instead of a block filled this way. */
extern void __VERIFIER_nondet_memory(void *mem, size_t size);

/* SV-Comp's unreach-call property is checked against reachability of this
 * exact function; AssertRewriter rewrites assert(cond) to
 * `if (!(cond)) reach_error();`. Defined unconditionally here like
 * everything else in this header - an unused external-linkage function
 * costs nothing (unlike a static one, it draws no -Wunused-function
 * warning). CountingVisitor records the *call* site (not this definition)
 * so Verifier::selectProperties can still detect it per file. */
void reach_error(void) { assert(0); }

/* Bounds on synthesized symbolic state. Fixed for now (see argv-c-transformer's
 * HavocPolicy.hpp for the rationale behind each value); a config-driven
 * pipeline run would need to regenerate this file instead of copying it
 * verbatim. */
#define __HAVOC_ARGC_MIN 1
#define __HAVOC_ARGC_MAX 4
#define __HAVOC_STR_MAX 16
#define __HAVOC_BLOCK_MAX 128

/* Havocked opaque pointer storage: a stack block of __HAVOC_BLOCK_MAX bytes,
 * filled with nondet bytes. Must be a macro, not a function - a function
 * cannot safely return a pointer to its own stack storage, which is exactly
 * the dangling-pointer bug this scaffolding exists to avoid. */
#define __HAVOC_BLOCK()                                                                          \
  (({                                                                                             \
    unsigned char __havoc_blk[__HAVOC_BLOCK_MAX];                                                 \
    __VERIFIER_nondet_memory(__havoc_blk, __HAVOC_BLOCK_MAX);                                     \
    __havoc_blk;                                                                                  \
  }))

/* Havocked C string storage: like __HAVOC_BLOCK, but null-terminated at a
 * nondet in-bounds offset so string operations stay in bounds. */
#define __HAVOC_CSTRING()                                                                         \
  (({                                                                                             \
    char __havoc_str[__HAVOC_BLOCK_MAX];                                                          \
    __VERIFIER_nondet_memory(__havoc_str, __HAVOC_BLOCK_MAX);                                     \
    size_t __havoc_len = __VERIFIER_nondet_size_t();                                              \
    if (__havoc_len >= __HAVOC_BLOCK_MAX)                                                         \
      abort();                                                                                    \
    __havoc_str[__havoc_len] = 0;                                                                 \
    __havoc_str;                                                                                  \
  }))

/* Havocked, bounded argc. Safe as a real function - returned by value, no
 * storage lifetime to worry about (unlike __HAVOC_BLOCK/__HAVOC_CSTRING). */
static inline int __havoc_argc(void) {
  int argc = __VERIFIER_nondet_int();
  if (argc < __HAVOC_ARGC_MIN || argc > __HAVOC_ARGC_MAX)
    abort();
  return argc;
}
#define __HAVOC_ARGC() __havoc_argc()

/* Havocked argv for a given argc (evaluated once): __HAVOC_ARGC_MAX+1
 * pointers, the first argc pointing into rows of a stack buffer filled with
 * havocked, null-terminated C strings, the rest null. Must be a macro, not a
 * function, for the same reason __HAVOC_BLOCK/__HAVOC_CSTRING are: the
 * backing storage has to live in the caller's own stack frame. Evaluates to
 * argv (array-to-pointer decay), so it's used directly as a call argument -
 * see MainGenConsumer::genMainHarness. */
#define __HAVOC_ARGV(argcExpr)                                                                   \
  (({                                                                                             \
    char __havoc_argv_buf[__HAVOC_ARGC_MAX][__HAVOC_STR_MAX];                                     \
    char *__havoc_argv_ptrs[__HAVOC_ARGC_MAX + 1];                                                \
    int __havoc_argv_argc = (argcExpr);                                                           \
    for (int __havoc_argv_i = 0; __havoc_argv_i < __havoc_argv_argc; __havoc_argv_i++) {          \
      __VERIFIER_nondet_memory(__havoc_argv_buf[__havoc_argv_i], __HAVOC_STR_MAX);                \
      size_t __havoc_argv_len = __VERIFIER_nondet_size_t();                                       \
      if (__havoc_argv_len >= __HAVOC_STR_MAX)                                                    \
        abort();                                                                                  \
      __havoc_argv_buf[__havoc_argv_i][__havoc_argv_len] = 0;                                     \
      __havoc_argv_ptrs[__havoc_argv_i] = __havoc_argv_buf[__havoc_argv_i];                       \
    }                                                                                              \
    __havoc_argv_ptrs[__havoc_argv_argc] = 0;                                                     \
    __havoc_argv_ptrs;                                                                            \
  }))

#endif /* ARGV_C_RUNTIME_H */
