/* SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Runtime scaffolding for benchmarks generated by argv-c.
 */

#ifndef ARGV_C_HARNESS_H
#define ARGV_C_HARNESS_H

#include <assert.h>
#include <stdlib.h>
#include <stddef.h>

/* SV-Comp nondet primitives. */
extern _Bool __VERIFIER_nondet_bool(void);
extern char __VERIFIER_nondet_char(void);
extern unsigned char __VERIFIER_nondet_uchar(void);
extern short __VERIFIER_nondet_short(void);
extern unsigned short __VERIFIER_nondet_ushort(void);
extern int __VERIFIER_nondet_int(void);
extern unsigned int __VERIFIER_nondet_uint(void);
extern long __VERIFIER_nondet_long(void);
extern unsigned long __VERIFIER_nondet_ulong(void);
extern long long __VERIFIER_nondet_longlong(void);
extern unsigned long long __VERIFIER_nondet_ulonglong(void);
extern float __VERIFIER_nondet_float(void);
extern double __VERIFIER_nondet_double(void);
extern size_t __VERIFIER_nondet_size_t(void);

/* Fills [mem, mem+size) with nondet bytes. Standard SV-Comp function
 * defined here per the rules' own reference implementation, since not
 * every verifier build has native support yet. */
void __VERIFIER_nondet_memory(void *mem, size_t size) {
  unsigned char *p = mem;
  for (size_t i = 0; i < size; i++) {
    p[i] = __VERIFIER_nondet_uchar();
  }
}

/* SV-Comp's unreach-call property is checked against reachability of this
 * exact function; AssertRewriter rewrites assert(cond) to
 * `if (!(cond)) reach_error();`. */
void reach_error(void) { assert(0); }

/* Havocked C string storage: null-terminated nondet_memory.
 * Used for havocking argv and at char-pointer return call sites*/
static inline char *__havoc_cstring_fill(char *buf, size_t cap) {
  __VERIFIER_nondet_memory(buf, cap);
  size_t len = __VERIFIER_nondet_size_t();
  if (len >= cap)
    abort();
  buf[len] = 0;
  return buf;
}

/* Bounds on synthesized symbolic state (__HAVOC_ARGC_MIN/MAX, __HAVOC_STR_MAX,
 * __HAVOC_BLOCK_MAX) are NOT defined here. Instead they are emitted per
 * benchmark and therefore tunable. */

/* Havocked, bounded argc (macros defined within each benchmark) */
static inline int __havoc_argc(void) {
  int argc = __VERIFIER_nondet_int();
  if (argc < __HAVOC_ARGC_MIN || argc > __HAVOC_ARGC_MAX)
    abort();
  return argc;
}
#define __HAVOC_ARGC() __havoc_argc()

/* Havocked, bounded argv */
static inline char **__havoc_argv_fill(int argc) {
  static char rows[__HAVOC_ARGC_MAX][__HAVOC_STR_MAX];
  static char *ptrs[__HAVOC_ARGC_MAX + 1];
  for (int i = 0; i < argc; i++) {
    ptrs[i] = __havoc_cstring_fill(rows[i], __HAVOC_STR_MAX);
  }
  ptrs[argc] = 0;
  return ptrs;
}

#endif /* ARGV_C_HARNESS_H */
