name: Build and Test CMake/Ninja on Multiple Platforms

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-on-all-OS:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Dependencies Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: >
          sudo apt-get update
          install -y 
          clang-20
          llvm-20
          clang-tools-20
          libclang-common-20-dev
          libclang-20-dev
          libclang1-20
          llvm-20-dev
      - name: Get Dependencies Mac
        if: ${{ matrix.os == 'macos-latest' }}
        run: >
          brew update
          brew install llvm
      - name: Get Dependencies Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: >
          choco install llvm
      - name: Configure CMake
        run: cmake -B build -S . -G Ninja
      - name: Build
        run: ninja -C build
      - name: Run Full
        run: ./build/full "$(clang -print-resource-dir)" samples/Tester/ properties.config
