name: Build and Test CMake/Ninja on Multiple Platforms

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-on-all-OS:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build -S . -G Ninja
      - name: Build
        run: ninja -C build
      - name: Run Full
        run: ./build/full "$(clang -print-resource-dir)" samples/Tester/ properties.config
