name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-on-all-OS:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Clang
      #   uses: actions/setup-clang@v3
      #   with:
      #     clang-version: 18
      - name: Run Full Transformer
        # run: ./fullRun.sh 
        run: |
          cmake -B build -S . -G Ninja
          ninja -C build
          ./build/full "$(clang -print-resource-dir)" samples/Tester/ properties.config
